name: module3_task0

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: "5 6 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Run help
      run: cd module3_task0 && make help
