---
name: release_drafter

"on":
  push:
  pull_request:

jobs:
  draft:
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}